Countdown timer
GcvKishore/TMS pull request #13
Opened 2022-04-02 18:08 UTC by Amulya301

Team,
Here are the files related to the timer tab. Please do review it and mention if any changes have to be made.

Thanks.

2022-04-02 18:11 UTC, GcvKishore approved these changes
All the files are updated as per the requirement.
Thanks.

2022-04-02 19:07 UTC, Vedvund requested changes
I felt it's a lot of CSS for a simple countdown page...
and maybe the bg01.jpg file can also be dropped because it is not been used in our project...

Please do check the requirements.txt as well because we strongly decided not to add the packages which we didn't use in the project. (optional change. it is not required for now but would be good practice)

I have attached the screenshot showing the view in my system. (only for confirmation)
![Screenshot from 2022-04-03 00-37-15](https://user-images.githubusercontent.com/86515503/161397749-bcfaa052-e589-482a-8e6c-b330c37e8b66.png)

2022-04-02 19:07 UTC, Vedvund commented on website/templates/website/index.html
> +			</form>
As the form doesn't store any email id or doesn't have any functionality. I guess we can drop it for now...

2022-04-03 14:53 UTC, GcvKishore approved these changes

2022-04-03 14:55 UTC, GcvKishore approved these changes

2022-04-03 17:33 UTC, Vedvund approved these changes
The code looks relevant and the website works all discussed

2022-04-04 04:37 UTC, priyushasunkara approved these changes
Looks good.

2022-04-04 04:38 UTC, merged