Delete option
GcvKishore/TMS pull request #21
Opened 2022-04-11 15:00 UTC by priyushasunkara

2022-04-11 15:08 UTC, GcvKishore approved these changes
Working as expected.

2022-04-11 15:20 UTC, Amulya301 approved these changes
Deleting exam and questions are working correctly.

2022-04-11 15:46 UTC, Vedvund commented on exam_app/views.py
> +
If you are not using this function you can delete it...

2022-04-11 15:53 UTC, Vedvund commented on exam_app/views.py
> +        MakeExam.objects.get(id = delete_exam).delete()
Here you are only deleting the exam objects and the questions related to the exam are still in the database. (In this case, you need to delete the related questions 1st)

Use this code before line 99
MakeQuestion.objects.filter(exam_model__id=delete_exam).delete()

2022-04-11 15:54 UTC, Vedvund requested changes
Added comments

2022-04-12 04:27 UTC, Vedvund approved these changes

2022-04-12 04:31 UTC, merged